name: CI Pipeline

on:
  push:
    branches:
      - main  # Запускается при пуше в главную ветку
  pull_request:
    branches:
      - main  # Запускается при создании pull request в главную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Выбор среды выполнения

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Шаг для извлечения кода из репозитория

      - name: Run a command
        run: echo "Hello, World!"  # Выполняет команду и выводит сообщение

  pwd:
    runs-on: ubuntu-latest

    steps:
      - name: pwd and ll
        run: pwd && ll
  
